Update to go version 1.21.1
exercism/go-test-runner pull request #108
Opened 2023-10-03 15:20 UTC by BramVanBerkel

In my exercises i came across a few instances where I was using go 1.21.1 locally, but the testrunner was running 1.20. This resulted in tests that passed locally, but not in the testrunner.

1.21 includes some new functions, most notably for me [new functions for slices](https://go.dev/blog/go1.21#:~:text=New%20slices%20package%20for%20common%20operations%20on%20slices%20of%20any%20element%20type.%20This%20includes%20sorting%20functions%20that%20are%20generally%20faster%20and%20more%20ergonomic%20than%20the%20sort%20package.)

We can also update the alpine image from 3.17 to 3.18 but was unsure if i also should include that in this PR, maybe that is better off in a new one.

2023-10-03 19:21 UTC, junedev commented
I am preliminary re-opening the PR to see what CI has to say about this. Not sure whether there were changes to the test outputs again which would mean this is more work than changing a number.

2023-10-04 06:21 UTC, ErikSchierboom approved these changes

2023-10-06 19:05 UTC, junedev requested changes
@BramVanBerkel I noticed that if the docker container uses 1.21, we also need to use that for our tests. I pushed that change to your PR but as expected some tests are failing now, probably because the test output changed slightly. Can you have a look at fixing the tests so this can be merged?

2023-10-22 19:09 UTC, BramVanBerkel commented
I've fixed the tests, can the workflows be ran? 😄

2023-10-23 12:15 UTC, junedev approved these changes

2023-10-23 12:20 UTC, merged